# Random Teleport Plugin Configuration
teleport-range:
  min-x: -10000
  max-x: 10000
  min-z: -10000
  max-z: 10000
max-attempts-per-teleport: 50

# Integration settings
avoid-griefprevention-claims: true
avoid-worldguard-regions: true

# Cooldown settings
cooldown-enabled: true
cooldown-seconds: 10 # Cooldown duration in seconds

# Action Bar Countdown settings
action-bar-countdown-enabled: true
action-bar-countdown-duration: 5 # Duration of countdown on action bar before teleporting (in seconds)
action-bar-countdown-interval: 1 # How often the action bar updates (in seconds)

# Messages (optional, but good practice)
messages:
  teleporting: "&aAttempting to find a safe random location..."
  teleport-success: "&aYou have been teleported to X: %x%, Y: %y%, Z: %z%"
  no-safe-location: "&cCould not find a safe location after %attempts% attempts. Please try again."
  player-only: "&cOnly players can use this command."
  no-permission: "&cYou don't have permission to use this command."
  cooldown-active: "&cYou are on cooldown! Please wait %time% seconds."
  teleport-countdown: "&aTeleporting in %time% seconds..."
  
  # Thank you for using Secure RTP!!
  # If you enjoy my plugins, please consider
  # donating or subscribing to my YouTube @GigaMuffin :)